### ISSUE TITLE
SD Card

### ISSUE THREAD

**Issue by 20kvnk** [kunalgrover05/traffic-monitoring-scanner#2]
Even though the .mbt file is to be opened by the code before scanning to write all data to the file,
the program however failed to open the file each time it was tested.
Needs to be addressed

**Comment by kunalgrover05** [comment]
Have you setup the hardware correctly? See 4.9.1 in from http://labs.mediatek.com/fileMedia/download/5fed7907-b2ba-4000-bcb2-016a332a49fd

What does `SD.begin()`return? It returns true if SD was initialized properly.

**Comment by kunalgrover05** [comment]
Please finish your Pull Request so that we can close this issue.
